services:
  - type: web
    name: fabcity-chat-widget
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: N8N_WEBHOOK_URL
        value: https://automations.manymangoes.com.au/webhook/6b51b51f-4928-48fd-b5fd-b39c34f523d1/chat

